import { OWNER } from '../core/constants.js';

const P = OWNER.PLAYER;
const N = OWNER.NEUTRAL;
const AI = OWNER.ENEMY;

function n(id, type, x, y, owner = N) {
  return { id, type, x, y, owner };
}
function dormant(id, x, y) {
  return { id, type: 'workstation', x, y, owner: N, dormant: true };
}

export const LEVELS = [
  {
    code: '01',
    name: 'HANDSHAKE',
    briefing: 'Протяни канал. Перекачай буфер. Возьми соседа.',
    hasOpponent: false,
    objective: 'conquest',
    nodes: [
      n('p1', 'workstation', 0.18, 0.5, P),
      n('n2', 'workstation', 0.45, 0.28, N),
      n('n3', 'workstation', 0.45, 0.72, N),
      n('n4', 'workstation', 0.76, 0.5, N),
    ],
    edges: [
      ['p1', 'n2'],
      ['p1', 'n3'],
      ['n2', 'n4'],
      ['n3', 'n4'],
    ],
  },
  {
    code: '02',
    name: 'UPLINK',
    briefing: 'На проводе кто-то ещё. Не дай ему добраться первым.',
    hasOpponent: true,
    aiLevel: 2,
    objective: 'conquest',
    nodes: [
      n('p1', 'workstation', 0.12, 0.5, P),
      n('a', 'workstation', 0.36, 0.28, N),
      n('b', 'workstation', 0.36, 0.72, N),
      n('c', 'workstation', 0.64, 0.28, N),
      n('d', 'workstation', 0.64, 0.72, N),
      n('e1', 'workstation', 0.88, 0.5, AI),
    ],
    edges: [
      ['p1', 'a'],
      ['p1', 'b'],
      ['a', 'b'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'd'],
      ['c', 'e1'],
      ['d', 'e1'],
    ],
  },
  {
    code: '03',
    name: 'BACKBONE',
    briefing: 'Роутер ничего не производит. И решает всё.',
    hasOpponent: true,
    aiLevel: 3,
    objective: 'conquest',
    nodes: [
      n('p1', 'workstation', 0.08, 0.5, P),
      n('r1', 'router', 0.3, 0.5, N),
      n('a', 'workstation', 0.3, 0.22, N),
      n('b', 'workstation', 0.3, 0.78, N),
      n('r2', 'router', 0.7, 0.5, N),
      n('c', 'workstation', 0.7, 0.22, N),
      n('d', 'workstation', 0.7, 0.78, N),
      n('e1', 'workstation', 0.92, 0.5, AI),
    ],
    edges: [
      ['p1', 'r1'],
      ['r1', 'a'],
      ['r1', 'b'],
      ['r1', 'r2'],
      ['a', 'r2'],
      ['b', 'r2'],
      ['r2', 'c'],
      ['r2', 'd'],
      ['r2', 'e1'],
      ['c', 'e1'],
      ['d', 'e1'],
    ],
  },
  {
    code: '04',
    name: 'HARDENED',
    briefing: 'Фаервол в центре. Лобовая атака — самый дорогой размен на карте.',
    hasOpponent: true,
    aiLevel: 4,
    objective: 'conquest',
    nodes: [
      n('p1', 'workstation', 0.08, 0.5, P),
      n('a', 'workstation', 0.3, 0.28, N),
      n('b', 'workstation', 0.3, 0.72, N),
      n('f1', 'firewall', 0.5, 0.5, N),
      n('c', 'workstation', 0.7, 0.28, N),
      n('d', 'workstation', 0.7, 0.72, N),
      n('e1', 'workstation', 0.92, 0.5, AI),
    ],
    edges: [
      ['p1', 'a'],
      ['p1', 'b'],
      ['a', 'f1'],
      ['b', 'f1'],
      ['f1', 'c'],
      ['f1', 'd'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'e1'],
      ['d', 'e1'],
    ],
  },
  {
    code: '05',
    name: 'COLD STORAGE',
    briefing: 'Сервер отдаёт мало, но держит бесконечно. Вкладывайся вдолгую.',
    hasOpponent: true,
    aiLevel: 5,
    objective: 'conquest',
    nodes: [
      n('p1', 'workstation', 0.1, 0.5, P),
      n('s1', 'server', 0.35, 0.28, N),
      n('s2', 'server', 0.35, 0.72, N),
      n('m', 'workstation', 0.5, 0.5, N),
      n('s3', 'server', 0.65, 0.28, N),
      n('s4', 'server', 0.65, 0.72, N),
      n('e1', 'workstation', 0.9, 0.5, AI),
    ],
    edges: [
      ['p1', 's1'],
      ['p1', 's2'],
      ['s1', 'm'],
      ['s2', 'm'],
      ['m', 's3'],
      ['m', 's4'],
      ['s1', 's3'],
      ['s2', 's4'],
      ['s3', 'e1'],
      ['s4', 'e1'],
    ],
  },
  {
    code: '06',
    name: 'DEAD AIR',
    briefing: 'Спящие узлы по краям. Дёшево, если есть лишнее.',
    hasOpponent: true,
    aiLevel: 6,
    objective: 'conquest',
    nodes: [
      n('p1', 'workstation', 0.15, 0.5, P),
      n('a', 'workstation', 0.4, 0.35, N),
      n('b', 'workstation', 0.4, 0.65, N),
      n('c', 'workstation', 0.6, 0.35, N),
      n('d', 'workstation', 0.6, 0.65, N),
      n('e1', 'workstation', 0.85, 0.5, AI),
      dormant('dm1', 0.15, 0.15),
      dormant('dm2', 0.15, 0.85),
      dormant('dm3', 0.85, 0.15),
      dormant('dm4', 0.85, 0.85),
      dormant('dm5', 0.5, 0.1),
      dormant('dm6', 0.5, 0.9),
    ],
    edges: [
      ['p1', 'a'],
      ['p1', 'b'],
      ['a', 'b'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'd'],
      ['c', 'e1'],
      ['d', 'e1'],
      ['p1', 'dm1', { dashed: true }],
      ['p1', 'dm2', { dashed: true }],
      ['e1', 'dm3', { dashed: true }],
      ['e1', 'dm4', { dashed: true }],
      ['a', 'dm5', { dashed: true }],
      ['c', 'dm5', { dashed: true }],
      ['b', 'dm6', { dashed: true }],
      ['d', 'dm6', { dashed: true }],
    ],
  },
  {
    code: '07',
    name: 'THE CORE',
    briefing: 'Мейнфрейм в центре. Удержи двадцать секунд.',
    hasOpponent: true,
    aiLevel: 7,
    objective: 'hold',
    holdDuration: 20,
    mainframeId: 'mf',
    nodes: [
      n('p1', 'workstation', 0.1, 0.5, P),
      n('a', 'workstation', 0.3, 0.28, N),
      n('b', 'workstation', 0.3, 0.72, N),
      n('mf', 'mainframe', 0.5, 0.5, N),
      n('c', 'workstation', 0.7, 0.28, N),
      n('d', 'workstation', 0.7, 0.72, N),
      n('e1', 'workstation', 0.9, 0.5, AI),
    ],
    edges: [
      ['p1', 'a'],
      ['p1', 'b'],
      ['a', 'mf'],
      ['b', 'mf'],
      ['mf', 'c'],
      ['mf', 'd'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'e1'],
      ['d', 'e1'],
    ],
  },
  {
    code: '08',
    name: 'TRACED',
    briefing: 'Каждый удар слышен. Бей дозированно.',
    hasOpponent: true,
    aiLevel: 8,
    objective: 'conquest',
    trace: true,
    nodes: [
      n('p1', 'workstation', 0.1, 0.5, P),
      n('a', 'workstation', 0.3, 0.25, N),
      n('b', 'server', 0.3, 0.75, N),
      n('f1', 'firewall', 0.5, 0.5, N),
      n('c', 'server', 0.7, 0.25, N),
      n('d', 'workstation', 0.7, 0.75, N),
      n('e1', 'workstation', 0.9, 0.5, AI),
    ],
    edges: [
      ['p1', 'a'],
      ['p1', 'b'],
      ['a', 'f1'],
      ['b', 'f1'],
      ['f1', 'c'],
      ['f1', 'd'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'e1'],
      ['d', 'e1'],
    ],
  },
  {
    code: '09',
    name: 'EXFIL',
    briefing: 'Шестьдесят терабайт. Мейнфрейм должен быть твоим, пока идёт счёт.',
    hasOpponent: true,
    aiLevel: 9,
    objective: 'exfil',
    trace: true,
    holdDuration: 40,
    exfilTarget: 60,
    mainframeId: 'mf',
    nodes: [
      n('p1', 'workstation', 0.08, 0.5, P),
      n('a', 'workstation', 0.28, 0.28, N),
      n('b', 'server', 0.28, 0.72, N),
      n('mf', 'mainframe', 0.5, 0.5, N),
      n('c', 'server', 0.72, 0.28, N),
      n('d', 'workstation', 0.72, 0.72, N),
      n('e1', 'workstation', 0.92, 0.5, AI),
    ],
    edges: [
      ['p1', 'a'],
      ['p1', 'b'],
      ['a', 'mf'],
      ['b', 'mf'],
      ['mf', 'c'],
      ['mf', 'd'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'e1'],
      ['d', 'e1'],
    ],
  },
  {
    code: '10',
    name: 'BLACKSITE',
    briefing: 'Четырнадцать узлов. Всё сразу. Тридцать секунд на мейнфрейме.',
    hasOpponent: true,
    aiLevel: 10,
    objective: 'hold',
    trace: true,
    holdDuration: 30,
    mainframeId: 'mf',
    nodes: [
      n('p1', 'workstation', 0.05, 0.5, P),
      n('w1', 'workstation', 0.2, 0.2, N),
      n('w2', 'workstation', 0.2, 0.8, N),
      n('r1', 'router', 0.33, 0.3, N),
      n('r2', 'router', 0.33, 0.7, N),
      n('s1', 'server', 0.33, 0.5, N),
      n('f1', 'firewall', 0.5, 0.15, N),
      n('f2', 'firewall', 0.5, 0.85, N),
      n('mf', 'mainframe', 0.5, 0.5, N),
      n('s2', 'server', 0.67, 0.5, N),
      n('w3', 'workstation', 0.67, 0.3, N),
      n('w4', 'workstation', 0.67, 0.7, N),
      n('w5', 'workstation', 0.82, 0.2, N),
      n('e1', 'workstation', 0.95, 0.5, AI),
    ],
    edges: [
      ['p1', 'w1'],
      ['p1', 'w2'],
      ['w1', 'r1'],
      ['w2', 'r2'],
      ['r1', 'r2'],
      ['r1', 's1'],
      ['r2', 's1'],
      ['r1', 'f1'],
      ['r2', 'f2'],
      ['s1', 'mf'],
      ['f1', 'mf'],
      ['f2', 'mf'],
      ['mf', 's2'],
      ['s2', 'w3'],
      ['s2', 'w4'],
      ['w3', 'w5'],
      ['w4', 'w5'],
      ['w3', 'e1'],
      ['w4', 'e1'],
      ['w5', 'e1'],
    ],
  },
];

export function getLevel(index) {
  return LEVELS[index];
}
